### ISSUE TITLE
Nome

### ISSUE THREAD

**Issue by MateuSoneca** [MateuSoneca/Projeto_Frontend#10]

**Comment by josi43** [comment]
A ideia do aplicativo é "organizar seus filme".
Então acho que podemos usar algo nessa pegada:
Estante,
Organize,
MyMovies,
WatchingNow.

**Comment by Leonardosouls** [comment]
A ideia que tivemos foi Play-List , mas uma coisa que pensei foi no nosso site não damos play em nada e só para salvar os filmes/serie que já assistimos.
Talvez temos que repensar o nome do site

**Comment by MateuSoneca** [comment]
Eu gostei do "Play-List" pelo trocadilho, filmes e lista. 
E gostei do MyMovies também, é básico e simples.

**Comment by josi43** [comment]
Poderiamos usar algo misturando os dois nomes...
My PlayList
My MovieList
MyList

**Comment by MateuSoneca** [comment]
o que acham de MY MOVIELIST?

**Comment by josi43** [comment]
Melhor nome até agora!

**Comment by Leonardosouls** [comment]
Sim eu gostei desse nome.
