### ISSUE TITLE
Protótipo: Tela de Inicio do Site

### ISSUE THREAD

**Issue by MateuSoneca** [MateuSoneca/Projeto_Frontend#24]

**Comment by Leonardosouls** [comment]
essa seria a tela que eu fiz 



![Image](https://user-images.githubusercontent.com/101436195/234358048-1f583353-b792-4b8e-bf63-9b5942bc8802.png)

**Comment by Leonardosouls** [comment]
Adicionei uma nova linha oq vcs acham ?




![Image](https://user-images.githubusercontent.com/101436195/234394803-62f62378-76bf-4b8f-9236-71551c75b007.png)

**Comment by MateuSoneca** [comment]
achei bom meu querido friend @Leonardosouls
