### ISSUE TITLE
Cores

### ISSUE THREAD

**Issue by MateuSoneca** [MateuSoneca/Projeto_Frontend#3]

**Comment by MateuSoneca** [comment]
Primária: Cinza (#A6A6A6)
Secundária: Branco (#FFFFFF)
Terciária: Verde (#00BF63)

O que acham?

**Comment by josi43** [comment]
Prefiro laranja... mas ok 😐

**Comment by Leonardosouls** [comment]
gostei das cores , e também temos que determinar as outras cores que usaremos .

**Comment by MateuSoneca** [comment]
Vamos tentar com o laranja, o verde ficou muito forte

**Comment by MateuSoneca** [comment]
Primária: Cinza (#A6A6A6)
Secundária: Branco (#FFFFFF)
Terciária: Verde (#00FF5F)

Mudança na cor terciária.
