### ISSUE TITLE
Tipografia

### ISSUE THREAD

**Issue by MateuSoneca** [MateuSoneca/Projeto_Frontend#6]

**Comment by Leonardosouls** [comment]
A tipografia que poderíamos usar e a ROBOTO que tem no figma , que ela e a básica.

**Comment by josi43** [comment]
Usar as fontes da logo:
space crusades ( https://www.dafont.com/pt/space-crusaders.font?text=My+MovieList&back=theme )
star7 (https://www.dafont.com/pt/star7.font?text=My+MovieList )

**Comment by MateuSoneca** [comment]
Show!
