### ISSUE TITLE
Logotipo

### ISSUE THREAD

**Issue by MateuSoneca** [MateuSoneca/Projeto_Frontend#9]

**Comment by Leonardosouls** [comment]
![Image](https://user-images.githubusercontent.com/101436195/232343759-30ab698f-206b-4a5a-8453-73aad89d5d64.png)

**Comment by Leonardosouls** [comment]
essa seria o nosso logotipo

**Comment by Leonardosouls** [comment]
![Image](https://user-images.githubusercontent.com/101436195/232343848-f8b53f19-01a8-475b-bb10-1d1481885216.png)

**Comment by Leonardosouls** [comment]
e essa seria a outra para usar no site

**Comment by josi43** [comment]
![Image](https://user-images.githubusercontent.com/56276811/234149381-3bc8e925-081b-446f-8c70-95650f652194.png)

**Comment by Leonardosouls** [comment]
eeeee mano eu acho que esta boa assim
